# Generated by Django 4.2.6 on 2023-10-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('phonographic_seal', models.CharField(blank=True, max_length=15, null=True, verbose_name='Selo Fotográfico')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('country', models.CharField(max_length=30, verbose_name='País')),
                ('gender', models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Mpb', 'Mpb'), ('Sertanejo', 'Sertanejo')], max_length=30, verbose_name='Gênero')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
            ],
        ),
    ]
